[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/freetype"

[[constraint]]
  name = "github.com/fogleman/gg"
  version = "1.1.0"

[[constraint]]
  name = "github.com/oliamb/cutter"
  version = "0.2.2"
